### ISSUE TITLE
Enhanced colorization

### ISSUE THREAD

**Issue by mpartipilo** [jeff-hykin/better-go-syntax#9]
One of my main problems with our large codebase is that some functions change or interact with global variables. I'd like to style them differently for Go.

According to https://code.visualstudio.com/docs/cpp/colorization-cpp it looks like C++ has this on vscode, but I'm trying the same with Go and it does not work, which leads me to assume that support for this needs to be added somewhere.

Would you be able to provide guidance on how to achieve this?

**Comment by jeff-hykin** [comment]
So the enhanced colorization of C++ is handled by the C++ extension, which has a language server built into it. So there's a similar Go extension [here](https://marketplace.visualstudio.com/items?itemName=ms-vscode.Go) but I don't know that they have a language server. Search or post on their repo and that should get you the current status of go enhanced colorization 👍
